project:
  type: website
  output-dir: docs

website:
  title: "Les Ruches 🐝"
  navbar:
    background: light
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Construire"
        href: pages/construire.qmd
      - href: pages/mesures-immediates.qmd
        text: "Tout de suite"
      - text: "Économie"
        href: pages/economie.qmd
      - text: "Écologie"
        href: pages/ecologie.qmd
      - text: "Social"
        href: pages/social.qmd
      - text: "Éducation"
        href: pages/education.qmd
      - text: "Institutions"
        href: pages/institutions.qmd


  page-navigation: true
  sidebar:
    - title: "Informations"
      style: floating
      alignment: right
      contents:
        - text: "Les Ruches : une synthèse de \"Comment fabriquer une guillotine\" de Juan Branco"
        - text: "Liens"
          contents:
            - text: "Twitter"
              href: https://x.com/anatolium
            - text: "Discord"
              href: https://discord.com/channels/1317888170628485200/1318638881956171857
            - text: "Keybase"
              href: https://keybase.io/lesruches
            - text: "PDF original"
              href: https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf
            - text: "GitHub"
              href: https://github.com/stefw/lesruches

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-title: "Sommaire"
    number-sections: true
    mainfont: "Linux Libertine"
    page-layout: full
    minimal: true
    compress: true
    lang: fr
    date-format: "DD/MM/YYYY HH:mm"