# Construire

La reconstruction de la France passera par une mobilisation totale des forces vives de la nation et une redéfinition profonde de nos rapports sociaux et productifs. Cette refondation s'appuiera sur quatre lois de programmation souveraine touchant la santé, l'énergie, l'enseignement et le numérique, offrant des réponses concrètes en termes de sécurité, d'intimité, d'accès aux ressources et de liberté. La France redeviendra une exception, éloignée des compétitions-monde qui nous écrasent, en recréant un appareil productif autonome et en restaurant la fierté de ses corps d'État, notamment médicaux et éducationnels.

## Refondation Nationale

### Lois de Programmation Souveraine
> "Quatre lois de programmation souveraine seront adoptées sur les questions de santé, d'énergie, d'enseignement et de numérique, qui nous permettront d'offrir à nos concitoyens des réponses concrètes en termes de sécurité, intimité, accès aux ressources et liberté."  
> [ Comment fabriquer une guillotine 🐝 , p.8 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=8)

#### Santé et Sécurité Sanitaire
- Création d'une industrie pharmaceutique publique à vocation humanitaire
- Garantie d'accès universel aux soins et aux médicaments
- Protection de l'intimité médicale des citoyens
- Développement de la recherche médicale souveraine

#### Énergie et Autonomie
- Plan de transition énergétique souveraine
- Développement des énergies renouvelables nationales
- Sécurisation des approvisionnements énergétiques
- Réduction de la dépendance aux importations

#### Enseignement et Formation
- Revalorisation du statut des enseignants
- Introduction du plurilinguisme dès le CP
- Création d'un examen national d'entrée en sixième
- Renforcement des fondamentaux (histoire, langues, mathématiques)

#### Numérique et Souveraineté Digitale
- Établissement d'un réseau numérique unique et souverain
- Protection contre la surveillance de masse
- Sécurisation des données nationales
- Développement d'infrastructures numériques indépendantes

### Reconstruction de l'Appareil Productif
> "La France redeviendra une exception, éloignée des compétitions-monde qui nous écrasent, recréant un appareil productif autonome."  
> [ Comment fabriquer une guillotine 🐝 , p.7 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=7)

#### Autonomie Productive
- Recréation d'un appareil productif national
- Développement des industries stratégiques
- Relocalisation des productions essentielles
- Renforcement de l'indépendance économique

#### Exception Française
- Sortie des logiques de compétition mondiale
- Préservation des spécificités nationales
- Développement d'un modèle économique unique
- Protection des savoir-faire français

#### Indépendance Économique
- Contrôle des investissements étrangers
- Protection des secteurs stratégiques
- Développement de filières souveraines
- Maîtrise des chaînes d'approvisionnement

### Corps d'État et Service Public
> "Elles feront à nouveau des fonctionnaires médicaux et éducationnels les piliers et la fierté de notre pays, aux côtés des corps d'ingénierie et de recherche, qui seront entièrement refondus."  
> [ Comment fabriquer une guillotine 🐝 , p.8 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=8)

#### Corps Médicaux
- Revalorisation des fonctionnaires de santé
- Autonomie des établissements médicaux
- Renforcement de la formation médicale
- Développement de la recherche en santé

#### Corps Éducatifs
- Restauration de la fierté professionnelle
- Autonomie pédagogique renforcée
- Revalorisation des statuts
- Formation continue approfondie

#### Corps d'Ingénierie et Recherche
- Refonte complète des corps techniques
- Développement de la recherche publique
- Renforcement des moyens d'innovation
- Création de pôles d'excellence

## Transformations Institutionnelles

### Réforme des Pouvoirs
> "Dans la perspective d'une scission des fonctions exécutives en autant de pôles de décision, mettant ainsi fin à la fonction d'incarnation totale et archaïque tenue par le chef de l'État."  
> [ Comment fabriquer une guillotine 🐝 , p.31 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=31)

#### Exécutif
- Modification temporaire du mandat présidentiel
- Scission des fonctions exécutives
- Fin de l'incarnation totale du chef de l'État
- Création de pôles de décision multiples

#### Législatif
- Fusion des chambres parlementaires
- Transformation du Sénat en chambre du peuple
- Suppression du Conseil économique, social et écologique
- Renforcement des pouvoirs de l'Assemblée des communes

#### Territorial
- Élection de commissaires de la République
- Remplacement des préfets
- Instauration de mandats impératifs et révocatoires
- Référendums d'initiative citoyenne à choix multiples

### Justice et Contrôle
> "Institution d'un Tribunal révolutionnaire et d'un Comité de clémence visant à purger la République."  
> [ Comment fabriquer une guillotine 🐝 , p.32 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=32)

#### Institutions Judiciaires
- Création d'un Tribunal révolutionnaire
- Établissement d'un Comité de clémence
- Purge des institutions républicaines
- Réforme de la justice administrative

#### Contrôle Démocratique
- Mandats révocatoires
- Référendums citoyens
- Contrôle populaire des institutions
- Transparence administrative

### Souveraineté Européenne
> "Un référendum sur l'appartenance à l'Union européenne sera proposé."  
> [ Comment fabriquer une guillotine 🐝 , p.33 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=33)

#### Processus Référendaire
- Organisation dans les 24 mois
- Débat apartisan
- Neutralité des représentants en fonction
- Information complète des citoyens

#### Mesures Préparatoires
- Dispositions conservatoires
- Préparation d'une monnaie souveraine
- Sécurisation des systèmes financiers
- Protection des intérêts nationaux

## Transformations Économiques

### Lutte contre les Monopoles
> "Décomposition systémique des oligopoles et monopoles issus de l'État."  
> [ Comment fabriquer une guillotine 🐝 , p.34 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=34)

#### Régulation
- Nouvelles règles antitrust
- Procédures accélérées
- Démantèlement des oligopoles
- Contrôle des concentrations

#### Recomposition
- Restructuration des espaces privés
- Régulation de la commande publique
- Protection de la concurrence
- Prévention des positions dominantes

### Système Bancaire
> "Le gouvernorat de la Banque de France fera l'objet d'une élection."  
> [ Comment fabriquer une guillotine 🐝 , p.35 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=35)

#### Banque de France
- Élection du gouverneur
- Restauration des droits de tirage directs
- Indépendance monétaire
- Contrôle démocratique

#### Établissements Publics
- Création de banques publiques spécialisées
- Focus sur l'investissement productif
- Soutien à l'économie réelle
- Financement des secteurs stratégiques

### Médias et Communication
> "La déliaison des puissances de l'argent et de la communication."  
> [ Comment fabriquer une guillotine 🐝 , p.36 ](https://aurores.org/wp-content/uploads/2024/12/PROGRAMME-.pdf#page=36)

#### Réforme Médiatique
- Référendum sur l'indépendance des médias
- Nouveau système de financement
- Séparation des pouvoirs économiques
- Protection du pluralisme

#### Dispositifs Citoyens
- Multiplication des médias autogérés
- Création de fondations citoyennes
- Développement de la presse indépendante
- Soutien aux initiatives locales
